name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.1-r2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c8b0be81e68e371c29482d1d9998475a374be8641d2cbf0e05a73aa53cb4ab6"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
