name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.1-r5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87b77f162df218feb615244b542b30cbe669af6794062ec441cacc8137706d53"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
