name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3927cb0560fdb1a48c443def06db59d76fc79088dc71a60b6bc4bcf4e679a368"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
