name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.3-r7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4052a221589f0e88df7d666aeb93410e45a2da0dfeb4cbc79a981849f0f0461e"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
