name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.1-r0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30900c67d2d5e833462a18561919a8e2a2555b539d6418221c806f3adb78fdb5"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
