name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.1-r6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c7c91d9cdc02974b7dbc2bb271c8a37158a736da9ac6d7517f2a310bfe6077"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
