name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.1-r6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43b5694ec2d94132e7495ae5d27b075051f5e1a8dae3b88b4c08d111c0dd4205"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
