name = "GCPM-Losenone"
author = "ursamina, Nixieboluo"
version = "1.11.1-r1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44035ab0e6f2cf0cb878e16f9fd06b000e15572ec90f7fe43ecd6a228f49b7fe"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
